name: Gatling Tests

on:
  push:
    branches: [ main ]

jobs:
  gatling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run Gatling tests
        run: mvn gatling:test

      - name: Debug output
        run: ls -R target

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: target/gatling